const $=s=>document.querySelector(s);
const screens={start:$('#start-screen'),game:$('#game-screen'),history:$('#history-screen'),end:$('#end-screen')};
const KEY='una-vita-save-v2';
let state=null;
const baseTraits=()=>({empathy:0,courage:0,belonging:0,reflection:0,integrity:0,impulse:0,stress:0,avoidance:0,ambition:0,security:0,trust:0,resilience:0,peace:0});
const baseResources=()=>({money:0,career:0,relationships:0,health:0});
function show(name){Object.values(screens).forEach(x=>x.classList.remove('active'));screens[name].classList.add('active')}
function chapterFor(age){if(age<=11)return'Infanzia';if(age<=19)return'Adolescenza';if(age<=30)return'Giovinezza';if(age<=55)return'Età adulta';if(age<=70)return'Maturità';return'Vecchiaia'}
function newLife(){state={age:5,deathAge:76+Math.floor(Math.random()*18),traits:baseTraits(),resources:baseResources(),flags:{},seen:[],history:[],startedAt:Date.now()};save();show('game');nextEvent()}
function save(){localStorage.setItem(KEY,JSON.stringify(state));updateContinue()}
function load(){try{state=JSON.parse(localStorage.getItem(KEY));if(!state||!state.age)return newLife();state.traits={...baseTraits(),...(state.traits||{})};state.resources={...baseResources(),...(state.resources||{})};state.flags=state.flags||{};state.seen=state.seen||[];state.history=state.history||[];show('game');nextEvent()}catch(e){newLife()}}
function updateContinue(){const has=!!localStorage.getItem(KEY);$('#continue-btn').classList.toggle('hidden',!has)}
function matchesRequires(event){if(!event.requires)return true;return Object.entries(event.requires).every(([k,v])=>state.flags[k]===v)}
function candidates(){return LIFE_EVENTS.filter(e=>state.age>=e.minAge&&state.age<=e.maxAge&&!state.seen.includes(e.id)&&matchesRequires(e))}
function advanceAge(){const step=Math.max(2,Math.floor(Math.random()*5)+1);state.age=Math.min(state.deathAge,state.age+step)}
function nextEvent(){if(state.age>=state.deathAge)return endLife();let list=candidates();if(!list.length){state.age+=Math.max(1,Math.floor(Math.random()*3)+1);save();return nextEvent()}const weighted=list.flatMap(e=>Array(e.memory?2:1).fill(e));const event=weighted[Math.floor(Math.random()*weighted.length)];renderEvent(event)}
function statusText(value,positive,neutral,negative){if(value>=3)return positive;if(value<=-2)return negative;return neutral}
function updateStatus(){const r=state.resources,t=state.traits;$('#bond-status').textContent=statusText((r.relationships||0)+(t.belonging||0)/2,'Forti','Stabili','Fragili');$('#mind-status').textContent=(t.stress||0)>=5?'Sotto pressione':(t.peace||0)>=3?'Sereno':'Variabile';const total=(r.money||0)+(r.career||0)+(r.health||0);$('#life-status').textContent=total>=6?'Solida':total<=-3?'Difficile':'Normale'}
function renderEvent(event){$('#age-label').textContent=`${state.age} anni`;$('#chapter-label').textContent=chapterFor(state.age);$('#life-progress').style.width=`${Math.min(100,(state.age/state.deathAge)*100)}%`;updateStatus();const mem=$('#memory-note');if(event.memory){mem.textContent=`Ricordi: ${event.memory}`;mem.classList.remove('hidden')}else mem.classList.add('hidden');$('#context-label').textContent=event.context||'';$('#event-title').textContent=event.title;$('#event-text').textContent=event.text;const box=$('#choices');box.innerHTML='';event.choices.forEach((choice,i)=>{const b=document.createElement('button');b.className='choice';b.textContent=choice.text;b.onclick=()=>choose(event,choice,i);box.appendChild(b)});$('#echo').classList.add('hidden')}
function choose(event,choice,index){Object.entries(choice.effects||{}).forEach(([k,v])=>state.traits[k]=(state.traits[k]||0)+v);Object.entries(choice.resources||{}).forEach(([k,v])=>state.resources[k]=(state.resources[k]||0)+v);Object.assign(state.flags,choice.flags||{});state.seen.push(event.id);state.history.push({age:state.age,event:event.id,title:event.title,choice:choice.text,index,echo:choice.echo||''});$('#choices').innerHTML='';const echo=$('#echo');echo.textContent=choice.echo||'La vita continua.';echo.classList.remove('hidden');advanceAge();save();setTimeout(nextEvent,1050)}
function renderHistory(){const list=$('#history-list');list.innerHTML='';if(!state.history.length){list.innerHTML='<p class="lead">La tua storia deve ancora cominciare.</p>';return}state.history.forEach(h=>{const item=document.createElement('article');item.className='history-item';item.innerHTML=`<div class="history-age">${h.age} anni</div><div><h3>${h.title}</h3><p>${h.choice}</p></div>`;list.appendChild(item)})}
function describe(){const t=state.traits,r=state.resources,lines=[];if(t.empathy>=5)lines.push('Hai imparato a vedere gli altri, anche quando sarebbe stato più semplice ignorarli.');else if(t.empathy<=-2)lines.push('Spesso hai protetto te stesso prima degli altri.');if(t.courage>=5)lines.push('Hai scelto più volte l’incertezza invece della sicurezza.');if(t.integrity>=4)lines.push('Hai rinunciato ad alcune scorciatoie pur di restare fedele a te stesso.');if(t.ambition>=5)lines.push('Hai inseguito ciò che volevi con ostinazione, pagando qualche prezzo lungo la strada.');if(t.belonging>=5||r.relationships>=4)lines.push('I legami hanno avuto un peso enorme nella tua vita.');if(t.avoidance>=5)lines.push('Alcune conversazioni sono rimaste sospese troppo a lungo.');if(state.flags.deepLove)lines.push('Hai lasciato che almeno una persona ti conoscesse davvero.');if(state.flags.hasChild&&state.flags.repairedChildBond)lines.push('Hai trovato il coraggio di riparare almeno una distanza che avevi contribuito a creare.');if(state.flags.reconciled)lines.push('Verso la fine hai riaperto una porta che credevi chiusa.');if(r.career>=5)lines.push('Il lavoro ti ha dato identità e risultati, ma ha occupato una parte importante del tuo tempo.');if(r.health<=-3)lines.push('Il corpo ha portato con sé alcune conseguenze di scelte rimandate troppo a lungo.');if(t.peace>=3)lines.push('Alla fine non hai avuto bisogno che tutto fosse perfetto per riconoscere la tua vita come tua.');if(!lines.length)lines.push('Hai vissuto senza una direzione semplice da riassumere. Forse è proprio questo che la rende una vita.');return lines.slice(0,6)}
function summaryLabel(v,high,mid,low){return v>=4?high:v<=-2?low:mid}
function renderSummary(){const r=state.resources;const cards=[['Relazioni',summaryLabel(r.relationships,'Profonde','Complesse','Distanti')],['Lavoro',summaryLabel(r.career,'Realizzato','Normale','Instabile')],['Salute',summaryLabel(r.health,'Curata','Variabile','Fragile')]];const box=$('#life-summary');box.innerHTML='';cards.forEach(([a,b])=>{const d=document.createElement('div');d.className='summary-card';d.innerHTML=`<span>${a}</span><strong>${b}</strong>`;box.appendChild(d)})}
function endLife(){show('end');$('#end-years').textContent=`Hai vissuto ${state.deathAge} anni. ${state.history.length} scelte importanti hanno lasciato una traccia.`;renderSummary();const ep=$('#epitaph');ep.innerHTML='';describe().forEach(x=>{const p=document.createElement('p');p.textContent=x;ep.appendChild(p)});localStorage.removeItem(KEY);updateContinue()}
$('#start-btn').onclick=newLife;$('#continue-btn').onclick=load;$('#restart-btn').onclick=newLife;$('#history-btn').onclick=()=>{renderHistory();show('history')};$('#history-back').onclick=()=>show('game');updateContinue();
