window.LIFE_EVENTS=[
{id:'child_friend',minAge:5,maxAge:8,chapter:'Infanzia',context:'Cortile della scuola',title:'Il bambino nuovo',text:'Un bambino appena arrivato resta solo durante la ricreazione. Gli altri lo ignorano.',choices:[{text:'Vado a parlargli.',effects:{empathy:2,courage:1,belonging:1},echo:'Ti ricorderai di aver scelto di avvicinarti.'},{text:'Resto con il mio gruppo.',effects:{belonging:1,empathy:-1},echo:'Hai imparato che stare al sicuro nel gruppo è più facile.'},{text:'Lo osservo, ma non faccio nulla.',effects:{reflection:1,courage:-1},echo:'A volte non scegliere è comunque una scelta.'}]},
{id:'child_truth',minAge:7,maxAge:11,chapter:'Infanzia',context:'Casa',title:'Il vaso rotto',text:'Hai rotto per sbaglio un vaso importante. Nessuno ti ha visto.',choices:[{text:'Dico subito la verità.',effects:{integrity:2,courage:1,stress:1},echo:'La paura passa. La memoria della scelta resta.'},{text:'Do la colpa a qualcun altro.',effects:{integrity:-2,impulse:1,stress:2},echo:'La bugia ti protegge adesso, ma cambia il modo in cui ti guardi.'},{text:'Nascondo tutto e spero che nessuno scopra nulla.',effects:{avoidance:2,stress:1},echo:'Hai scoperto quanto è facile rimandare le conseguenze.'}]},
{id:'teen_mock',minAge:12,maxAge:16,chapter:'Adolescenza',context:'Scuola',title:'Tutti stanno ridendo',text:'Un compagno viene umiliato davanti alla classe. Ridere ti renderebbe parte del gruppo.',choices:[{text:'Lo difendo davanti a tutti.',effects:{courage:3,empathy:2,belonging:-1},echo:'Qualcuno non dimenticherà quello che hai fatto.'},{text:'Rido anch’io.',effects:{belonging:2,empathy:-2,integrity:-1},echo:'Per un momento sei dentro il gruppo. Non sai ancora il prezzo.'},{text:'Non rido, ma resto zitto.',effects:{reflection:1,courage:-1},echo:'Il silenzio ti accompagna più a lungo del previsto.'}]},
{id:'teen_future',minAge:16,maxAge:19,chapter:'Adolescenza',context:'Una sera d’estate',title:'Partire o restare',text:'Ti viene offerta un’occasione lontano da casa. Significa lasciare amici, abitudini e sicurezza.',choices:[{text:'Parto.',effects:{courage:2,ambition:2,belonging:-1},flags:{leftHome:true},echo:'Hai scelto l’incertezza.'},{text:'Resto.',effects:{belonging:2,security:2,ambition:-1},flags:{leftHome:false},echo:'Hai scelto ciò che conosci.'}]},
{id:'young_work',minAge:20,maxAge:29,chapter:'Giovinezza',context:'Lavoro',title:'Una scorciatoia',text:'Puoi ottenere un vantaggio importante facendo qualcosa che nessuno probabilmente scoprirà.',choices:[{text:'Rifiuto.',effects:{integrity:3,ambition:-1},echo:'Hai perso un vantaggio, ma conservato una parte di te.'},{text:'Accetto.',effects:{ambition:2,integrity:-2,stress:1},echo:'Funziona. Ed è proprio questo a rendere tutto più complicato.'}]},
{id:'young_love',minAge:24,maxAge:34,chapter:'Giovinezza',context:'Relazioni',title:'Una persona che ti conosce davvero',text:'La relazione diventa seria. Per continuare dovresti mostrare anche parti di te che tieni nascoste.',choices:[{text:'Mi apro davvero.',effects:{trust:3,belonging:2,stress:-1},flags:{deepLove:true},echo:'Essere visti fa paura. Essere compresi ancora di più.'},{text:'Mantengo una distanza.',effects:{avoidance:2,security:1,trust:-2},flags:{deepLove:false},echo:'Ti proteggi. Ma la protezione lascia fuori anche qualcosa di buono.'}]},
{id:'adult_family',minAge:32,maxAge:48,chapter:'Età adulta',context:'Famiglia',title:'Il tempo che non basta',text:'Il lavoro ti chiede sempre di più. Una persona importante per te ha bisogno della tua presenza.',choices:[{text:'Rinuncio a un’opportunità e resto.',effects:{belonging:3,ambition:-2,empathy:1},flags:{choseFamily:true},echo:'Non saprai mai fino in fondo cosa hai lasciato andare.'},{text:'Scelgo il lavoro.',effects:{ambition:3,belonging:-2,stress:1},flags:{choseFamily:false},echo:'Alcune porte si aprono mentre altre si chiudono in silenzio.'}]},
{id:'adult_failure',minAge:40,maxAge:57,chapter:'Età adulta',context:'Un periodo difficile',title:'Hai fallito',text:'Un progetto importante crolla. Hai perso denaro, reputazione o fiducia. Puoi ricominciare oppure ritirarti.',choices:[{text:'Ricomincio da zero.',effects:{resilience:3,courage:2,stress:1},echo:'Non torni quello di prima. Costruisci qualcuno di nuovo.'},{text:'Mi accontento di una vita più sicura.',effects:{security:2,ambition:-2,stress:-1},echo:'La pace può essere una conquista o una rinuncia.'}]},
{id:'mature_parent',minAge:58,maxAge:70,chapter:'Maturità',context:'Una telefonata',title:'Qualcuno del passato',text:'Una persona con cui hai chiuso male molti anni fa ti cerca. Non sai quanto tempo vi resti.',choices:[{text:'Rispondo.',effects:{empathy:2,trust:1,stress:-1},flags:{reconciled:true},echo:'Non tutto si aggiusta. Ma qualcosa può ancora cambiare.'},{text:'Non rispondo.',effects:{avoidance:2,stress:1},flags:{reconciled:false},echo:'Anche le porte chiuse continuano a esistere.'}]},
{id:'old_reflect',minAge:71,maxAge:88,chapter:'Vecchiaia',context:'Una mattina tranquilla',title:'La tua vita davanti a te',text:'Ripensi alle persone, alle occasioni, agli errori e alle cose che hai salvato. Cosa senti più forte?',choices:[{text:'Gratitudine.',effects:{peace:3},echo:'Non perché tutto sia andato bene, ma perché è stato tuo.'},{text:'Rimpianto.',effects:{reflection:3,peace:-1},echo:'Le vite non vissute sembrano sempre perfette da lontano.'},{text:'Curiosità.',effects:{reflection:2,peace:1},echo:'Anche adesso, una parte di te vuole sapere cosa viene dopo.'}]}
];
